### ISSUE TITLE
installation on Linux

### ISSUE THREAD

**Issue by mbflex** [RobertMyles/tidyRSS#12]
I like your package very much - thanks for sharing it!

I tried to use it on Linux machine as well.
This means, I tried to install it on a Linux machine: "install.packages("tidyRSS")"

I had to add several Linux libraries for this:
sudo apt-get install libudunits2-dev
sudo apt-get install libcurl4-openssl-dev 
sudo apt-get install libxml2-dev
sudo apt-get install gdal-bin
sudo apt-get install libgdal-dev

However, even with all this stuff, it did not work:
configure: GDAL: 1.10.1
checking GDAL version >= 2.0.0... no
**configure: error: sf is not compatible with GDAL versions below 2.0.0**

Actually, I do not understand why a RRS feed package depends on an "software library for reading and writing raster and vector geospatial data formats".  

At the end - I gave up, at least for the Linux side.
No way to make it less complex?

**Comment by RobertMyles** [comment]
Hmm, that's unfortunate! I'm using sf to work with the geoRSS feeds. These are new to the package, so previous versions would have worked fine for you.

This might help: [https://stackoverflow.com/questions/46770637/fail-to-upgrade-rgdal](https://stackoverflow.com/questions/46770637/fail-to-upgrade-rgdal)

Otherwise, you could fork the repo and take out the sf-related and geoRSS-related stuff and have a private version of tidyRSS until you can fix that gdal problem.

**Comment by RobertMyles** [comment]
@mbflex all these dependencies are removed now, in case you'd like to use tidyRSS again.
