### ISSUE TITLE
Not getting full RSS tree

### ISSUE THREAD

**Issue by b-w-a** [RobertMyles/tidyRSS#15]
HI there - trying to get this:  

`result <- tidyfeed(feed = "https://www.fandango.com/rss/moviesnearme_90025.rss")`

But I only get the movie theatre locations, not the movies playing at that location. Any suggestions?

**Comment by RobertMyles** [comment]
Hi,

That's a weird one, it should come back with the 'description' field. I'm getting errors regardless, so I need to do some work on the package, I've been too busy to come back to it lately. I'm going to close this because there are some bigger problems that need to be fixed and it'll probably get fixed with those, in the next version. Thanks for letting me know about the problem.
