### ISSUE TITLE
List of rss/Atom feeds that are not parsing correctly

### ISSUE THREAD

**Issue by RobertMyles** [RobertMyles/tidyRSS#3]
https://hayobethlehem.nl/feed/atom/   
 
- returns error  (issue on xml2 repo)

http://w3future.com/weblog/rss.xml?notransform   
- returns error  
- malformed

http://www.intertwingly.net/blog/index.atom 
 - mix up with link
- works

http://newsrss.bbc.co.uk/rss/newsonline_world_edition/front_page/rss.xml  
 - works

**Comment by dfalbel** [comment]
@RobertMyles   this feed has 3 entries but returns only a data.frame with 2 rows:

http://lurodrigo.com/feed.R_pt.xml 

```
> k <- tidyRSS::tidyfeed("http://lurodrigo.com/feed.R_pt.xml")
> head(k)
# A tibble: 2 x 8
    feed_title                    feed_link                  feed_author         feed_last_updated
         <chr>                        <chr>                        <chr>                     <chr>
1 Luiz Rodrigo https://lurodrigo.github.io/ Luiz Rodrigome@lurodrigo.com 2017-06-15T17:30:41-03:00
2 Luiz Rodrigo https://lurodrigo.github.io/ Luiz Rodrigome@lurodrigo.com 2017-06-15T17:30:41-03:00
# ... with 4 more variables: item_title <chr>, item_date_updated <dttm>, item_link <chr>, item_content <chr>
```

Am I doing something wrong?

**Comment by RobertMyles** [comment]
Nope, doing nothing wrong, it was the way I was using Xpath for Atom feeds. Fixed now: 

```
> tidyfeed("http://lurodrigo.com/feed.R_pt.xml")
# A tibble: 3 x 8
    feed_title                    feed_link                  feed_author
         <chr>                        <chr>                        <chr>
1 Luiz Rodrigo https://lurodrigo.github.io/ Luiz Rodrigome@lurodrigo.com
2 Luiz Rodrigo https://lurodrigo.github.io/ Luiz Rodrigome@lurodrigo.com
3 Luiz Rodrigo https://lurodrigo.github.io/ Luiz Rodrigome@lurodrigo.com
# ... with 5 more variables: feed_last_updated <chr>, item_title <chr>,
#   item_date_updated <dttm>, item_link <chr>, item_content <chr>
```

This will work in the dev version, I'm submitting to CRAN now.

**Comment by dfalbel** [comment]
Great! Thanks!

**Comment by lodderig** [comment]
Google Alerts RSS the item_link contains the ID instead of the link
e.g. 

`>tidyfeed("https://www.google.com/alerts/feeds/03790873685617914995/10391961171333916339")

   feed_title   feed_link feed_last_updated item_title   item_date_updated   item_link  item_content  
   <chr>        <chr>     <chr>             <chr>        <dttm>              <chr>      <chr>         
 1 "Google Ale… ""        2018-11-09T21:45… UN Police W… 2018-11-09 21:45:00 tag:googl… ... and the S…
 2 "Google Ale… ""        2018-11-09T21:45… Amavubi sta… 2018-11-09 21:22:30 tag:googl… ... Hotel in …
 3 "Google Ale… ""        2018-11-09T21:45… Russian Mil… 2018-11-09 21:00:00 tag:googl… The Kremlin o…
 4 "Google Ale… ""        2018-11-09T21:45… The Congo&#… 2018-11-09 18:37:33 tag:googl… This is espec…
 5 "Google Ale… ""        2018-11-09T21:45… Algeria tes… 2018-11-09 17:26:15 tag:googl… ... Motema Pe…`

returns for the item_link

> rss$item_link[i]
[1] "tag:google.com,2013:googlealerts/feed:9086134150411630675"

**Comment by RobertMyles** [comment]
Thanks @lodderig, I'll have a look at it a.s.a.p.
